// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQj_iktUNsFejF9W6cLWPTgT8-0Y6NB4g',
    appId: '1:256961429508:web:4537add72d27e5df64b551',
    messagingSenderId: '256961429508',
    projectId: 'chat-app-96f45',
    authDomain: 'chat-app-96f45.firebaseapp.com',
    storageBucket: 'chat-app-96f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGSkc5KkMGgT6RMnD-YnHDBdfBoQ13L_8',
    appId: '1:256961429508:android:31dd2ca4474ddff464b551',
    messagingSenderId: '256961429508',
    projectId: 'chat-app-96f45',
    storageBucket: 'chat-app-96f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEMcZJ2EEHXOE_TYamyo3JZnUG-rjiOY',
    appId: '1:256961429508:ios:1e2e19e3978b583b64b551',
    messagingSenderId: '256961429508',
    projectId: 'chat-app-96f45',
    storageBucket: 'chat-app-96f45.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEMcZJ2EEHXOE_TYamyo3JZnUG-rjiOY',
    appId: '1:256961429508:ios:1e2e19e3978b583b64b551',
    messagingSenderId: '256961429508',
    projectId: 'chat-app-96f45',
    storageBucket: 'chat-app-96f45.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQj_iktUNsFejF9W6cLWPTgT8-0Y6NB4g',
    appId: '1:256961429508:web:06207cee00a6cea864b551',
    messagingSenderId: '256961429508',
    projectId: 'chat-app-96f45',
    authDomain: 'chat-app-96f45.firebaseapp.com',
    storageBucket: 'chat-app-96f45.appspot.com',
  );
}
